### PR TITLE
Upgrade tools and libraries

### PR DESCRIPTION
**Pull request by alexbirkett**
Target and compile with SDK 25
Use support lib 25.1.1
Use play-services 10.0.1
Use gradle 2.14.1

Add missing onAdBreakStatusUpdated() method to implementers of RemoteMediaClient.Listener

### CODE REVIEW

**Comment by alexbirkett** [comment]
I signed it!

**Comment by julioz** [comment]
@alexbirkett Can you confirm this introduces the "auto-connect" behavior described [here](https://code.google.com/p/android/issues/detail?id=232326)?
Thanks.

**Comment by alexbirkett** [comment]
If the telephone is restarted and then the Cast Video Sample app is started a connection is established to a Chromecast device. This is not what I would expect.

I did not experience the endlessly connect/disconnect issue described [here](https://code.google.com/p/android/issues/detail?id=232326) using the Cast Video Sample app but I have experienced it in a different app that uses the 25.1.1 support library.

**Comment by alexbirkett** [comment]
When I build the Cast Video Sample app against the 25.0.1 support library, a connection is not established to a Chromecast device when the app is started following a telephone reboot.

**Comment by barnhill** [comment]
opened https://github.com/googlecast/CastVideos-android/pull/44 ... hope this also fixes your issues but it updates it to a newer version of the dependencies.  I propose we close your pull and upvote mine to get them to even newer dependencies that actually let people build inside android studio 2.3.  Im wondering if they even monitor this repo anymore.

**Comment by julioz** [comment]
@barnhill I agree with you.
@alexbirkett The bug I mentioned before was introduced in Play Services 25.1.0 but is already fixed.

It is unfortunate we have that much turnaround time for this repository. Google requires lots of things on their [checklist](https://developers.google.com/cast/docs/design_checklist/) but is not providing all info for developers in order to comply with it.

**Comment by barnhill** [comment]
Haha they have abysmal turn around times.  I've got a defect fix in Android 7.0+ and it's been in code review for months and it's a single char change.

**Comment by LeonNicholls** [comment]
See latest updates.

**Comment by barnhill** [comment]
When you do update you go through them all :)

**Pull request closed without merging**
